def add(a,b):
    return a+b
def sub(a,b):
    return a-b
def mul(a,b):
    return a*b
def div(a,b):
    return a/b
def int_div(a,b):
    return a//b
def mod(a,b):
    return a%b
def pow(a,b):
    return a**b
def root(a,b):
    return a**(1/b)
name='Surya Module'
